### ISSUE TITLE
How long should 'make run' take?

### ISSUE THREAD

**Issue by jgfoster** [CS161/chickadee#1]
I've started it on two different machines. After about 40 hours of 100% CPU the '@' counter is at 13 million. What is the end state number? Did a delay accidentally get put into the releases?
![screen shot 2018-04-08 at 7 52 41 am](https://user-images.githubusercontent.com/1577872/38468936-dc165910-3b01-11e8-8b68-5e369833473b.png)

**Comment by jgfoster** [comment]
After 48 hours one VM ran out of disk space (having been given the 20 GB default). The other session is still running after 72 hours and the counter has reached 25.4 million.

**Comment by kohler** [comment]
Hi! Um, what were you expecting to happen here? The VM ran out of disk space because log.txt grew indefinitely.

**Comment by jgfoster** [comment]
I guess I misunderstood the instructions. I didn't realize that the system was running correctly once it started. Thanks!
